kubectl apply -f 1x/audio-and-video-cronjob.yaml
kubectl apply -f 1x/audio-only-cronjob.yaml
kubectl apply -f 1x/basic-cronjob.yaml
kubectl apply -f 1x/movement-audio-video-cronjob.yaml
kubectl apply -f 1x/movement-only-cronjob.yaml
kubectl apply -f 1x/video-only-cronjob.yaml
kubectl apply -f 2x/audio-and-video-cronjob.yaml
kubectl apply -f 2x/audio-only-cronjob.yaml
kubectl apply -f 2x/basic-cronjob.yaml
kubectl apply -f 2x/movement-audio-video-cronjob.yaml
kubectl apply -f 2x/movement-only-cronjob.yaml
kubectl apply -f 2x/video-only-cronjob.yaml
kubectl apply -f 4x/audio-and-video-cronjob.yaml
kubectl apply -f 4x/audio-only-cronjob.yaml
kubectl apply -f 4x/basic-cronjob.yaml
kubectl apply -f 4x/movement-audio-video-cronjob.yaml
kubectl apply -f 4x/movement-only-cronjob.yaml
kubectl apply -f 4x/video-only-cronjob.yaml
kubectl apply -f 8x/audio-and-video-cronjob.yaml
kubectl apply -f 8x/audio-only-cronjob.yaml
kubectl apply -f 8x/basic-cronjob.yaml
kubectl apply -f 8x/movement-audio-video-cronjob.yaml
kubectl apply -f 8x/movement-only-cronjob.yaml
kubectl apply -f 8x/video-only-cronjob.yaml