FROM ubuntu:latest

# Install required dependencies
RUN apt-get update && \
    apt-get install -y \
    git \
    curl 
    
# Install nodejs

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

# Install chrome
RUN curl -fsSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o chrome.deb && \
    dpkg -i chrome.deb || apt-get -y --fix-broken install && \
    apt-get install -y && \
    rm -rf /var/lib/apt/lists/* chrome.deb

RUN apt-get install -y google-chrome-stable 
# Clone the ir-engine repository
RUN git clone -b dev --depth 1 https://github.com/ir-engine/ir-engine.git /ir-engine

# Clone ir-development-test-suite and ir-bot inside ir-engine/packages/projects/projects/
WORKDIR /ir-engine/packages/projects/projects/
RUN git clone -b test/bot-test --depth 1 https://github.com/IREngine/ir-development-test-suite.git && \
    git clone -b test/bot-test --depth 1 https://github.com/IREngine/ir-bot.git

# Cleanup
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /get-docker.sh

# Set the working directory to /ir-engine
WORKDIR /ir-engine

RUN cp .env.local.default .env.local

RUN npm install --loglevel notice --legacy-peer-deps

WORKDIR /ir-engine/packages/projects/projects/ir-engine/ir-development-test-suite

ENV DOMAIN=test2.ir-engine.com
ENV LOCATION=default
ENV MOVEMENT=false
ENV AUDIO=false
ENV VIDEO=false
ENV END_MINUTE=59

CMD npx vite-node e2e/benchmark/run-bot --domain ${DOMAIN} --location ${LOCATION} --movement ${MOVEMENT} --audio ${AUDIO} --video ${VIDEO} --endMinute ${END_MINUTE}